window.AETHER_DATA = {
  brand: {
    name: "AETHER",
    tagline: "AI DISCOVERY OS",
    description: "为所有人提供简单、直观的 AI 工具发现系统。",
  },
  seo: {
    url: "https://ai-tools-directory-swart.vercel.app/",
    title: "AETHER — AI 工具导航与发现系统",
    description:
      "AETHER 是面向中文用户的 AI 工具导航，精选 AI 对话、绘图、视频、办公、编程和音乐工具，帮助用户快速找到合适的 AI 产品。",
    keywords: [
      "AI工具导航",
      "AI工具目录",
      "AI写作工具",
      "AI绘图工具",
      "AI视频工具",
      "AI编程工具",
      "AI办公工具",
    ],
  },
  categories: [
    "全部",
    "AI 对话",
    "图像设计",
    "视频创作",
    "办公效率",
    "编程开发",
    "音频音乐",
  ],
  keywords: ["写作", "绘图", "视频", "编程"],
  tools: [
    {
      name: "ChatGPT",
      description: "全能型 AI 助手，适合对话、写作、分析和日常创作。",
      category: "AI 对话",
      tags: ["热门", "写作"],
      url: "https://chatgpt.com/",
      accent: "#74aa9c",
      featured: true,
    },
    {
      name: "Claude",
      description: "擅长长文本理解、严谨写作和复杂任务协作。",
      category: "AI 对话",
      tags: ["长文本", "写作"],
      url: "https://claude.ai/",
      accent: "#d97757",
    },
    {
      name: "Gemini",
      description: "Google 推出的多模态 AI 助手，连接多种生产力服务。",
      category: "AI 对话",
      tags: ["多模态", "免费"],
      url: "https://gemini.google.com/",
      accent: "#4f86f7",
    },
    {
      name: "豆包",
      description: "面向中文用户的 AI 助手，覆盖问答、写作和图像生成。",
      category: "AI 对话",
      tags: ["中文", "免费"],
      url: "https://www.doubao.com/",
      accent: "#4975f7",
    },
    {
      name: "Midjourney",
      description: "高质量 AI 图像生成工具，适合概念设计与视觉创意。",
      category: "图像设计",
      tags: ["绘图", "热门"],
      url: "https://www.midjourney.com/",
      accent: "#f3f4f6",
      featured: true,
    },
    {
      name: "Canva AI",
      description: "在 Canva 中快速生成图片、文案和完整视觉设计。",
      category: "图像设计",
      tags: ["设计", "模板"],
      url: "https://www.canva.com/ai-image-generator/",
      accent: "#7d2ae8",
    },
    {
      name: "Adobe Firefly",
      description: "Adobe 的生成式创意工具，支持图像生成与智能编辑。",
      category: "图像设计",
      tags: ["绘图", "商用"],
      url: "https://firefly.adobe.com/",
      accent: "#ff5b35",
    },
    {
      name: "Runway",
      description: "专业 AI 视频生成与编辑平台，适合短片和商业创作。",
      category: "视频创作",
      tags: ["视频", "专业"],
      url: "https://runwayml.com/",
      accent: "#d8ff43",
      featured: true,
    },
    {
      name: "剪映",
      description: "一站式智能视频创作工具，提供字幕、数字人和智能剪辑。",
      category: "视频创作",
      tags: ["视频", "中文"],
      url: "https://www.capcut.cn/",
      accent: "#00e5ff",
    },
    {
      name: "Pika",
      description: "通过文字或图片快速生成短视频和创意特效。",
      category: "视频创作",
      tags: ["视频", "特效"],
      url: "https://pika.art/",
      accent: "#facc15",
    },
    {
      name: "Notion AI",
      description: "集成在 Notion 中的写作、总结和知识整理助手。",
      category: "办公效率",
      tags: ["写作", "笔记"],
      url: "https://www.notion.so/product/ai",
      accent: "#f5f5f5",
    },
    {
      name: "Gamma",
      description: "用 AI 快速创建演示文稿、文档和网页。",
      category: "办公效率",
      tags: ["PPT", "演示"],
      url: "https://gamma.app/",
      accent: "#a78bfa",
      featured: true,
    },
    {
      name: "Perplexity",
      description: "带来源引用的 AI 搜索工具，适合资料检索和研究。",
      category: "办公效率",
      tags: ["搜索", "研究"],
      url: "https://www.perplexity.ai/",
      accent: "#20b8cd",
    },
    {
      name: "Cursor",
      description: "以 AI 为核心的代码编辑器，支持生成、理解和修改项目。",
      category: "编程开发",
      tags: ["编程", "热门"],
      url: "https://www.cursor.com/",
      accent: "#e5e7eb",
      featured: true,
    },
    {
      name: "GitHub Copilot",
      description: "集成主流开发环境的 AI 编程助手与代码协作工具。",
      category: "编程开发",
      tags: ["编程", "开发"],
      url: "https://github.com/features/copilot",
      accent: "#8b5cf6",
    },
    {
      name: "Replit",
      description: "在浏览器中用 AI 构建、运行并部署应用。",
      category: "编程开发",
      tags: ["编程", "部署"],
      url: "https://replit.com/",
      accent: "#f26207",
    },
    {
      name: "Suno",
      description: "输入提示词即可生成完整歌曲、伴奏与人声。",
      category: "音频音乐",
      tags: ["音乐", "热门"],
      url: "https://suno.com/",
      accent: "#f43f5e",
      featured: true,
    },
    {
      name: "ElevenLabs",
      description: "高自然度 AI 语音生成、配音与声音设计平台。",
      category: "音频音乐",
      tags: ["语音", "配音"],
      url: "https://elevenlabs.io/",
      accent: "#e5e7eb",
    },
    {
      name: "Udio",
      description: "通过文字描述创作不同风格的完整音乐作品。",
      category: "音频音乐",
      tags: ["音乐", "创作"],
      url: "https://www.udio.com/",
      accent: "#60a5fa",
    },
  ],
  business: {
    email: "793679928@qq.com",
    wechat: "793679928",
    highlights: [
      {
        title: "高意向用户",
        description: "访问者正在主动寻找 AI 工具，比普通展示广告更接近试用和购买决策。",
      },
      {
        title: "首发友好",
        description: "适合新品冷启动、工具收录、品牌曝光和早期中文市场测试。",
      },
      {
        title: "人工审核",
        description: "所有商业内容都会标注广告或赞助，并人工确认素材、排期和展示位置。",
      },
      {
        title: "风险透明",
        description: "付费购买展示或优先审核，不承诺点击、成交、排名或永久收录。",
      },
    ],
    packages: [
      {
        id: "featured",
        name: "精选工具置顶",
        price: "¥99",
        period: "30 天",
        description: "分类内优先展示，并明确标注“赞助”。",
      },
      {
        id: "native",
        name: "内容流原生广告",
        price: "¥199",
        period: "30 天",
        description: "在工具列表中自然展示品牌与产品卖点。",
      },
      {
        id: "banner",
        name: "首页横幅",
        price: "¥299",
        period: "30 天",
        description: "占据首页核心曝光区域，适合新品发布。",
      },
      {
        id: "launch",
        name: "首发组合套餐",
        price: "¥499",
        period: "30 天",
        description: "精选置顶、内容流和首页横幅各一个。",
        recommended: true,
      },
      {
        id: "priority",
        name: "付费加急审核",
        price: "¥99",
        period: "单次",
        description: "优先审核工具资料，不保证收录或永久展示。",
      },
    ],
    disclaimer: "所有广告和加急服务均由人工确认。付费不保证流量、点击、成交或收录结果。",
    disclosure:
      "标注“广告”或“赞助”的内容属于付费展示。部分外链未来可能是联盟链接，网站可能获得佣金，但不会增加你的购买价格。",
    faq: [
      {
        question: "付款后工具一定会被收录吗？",
        answer: "不会。付费加急只代表优先审核，不保证通过、排名或永久展示。",
      },
      {
        question: "广告内容会明确标注吗？",
        answer: "会。广告、赞助和未来联盟链接都会明确披露，不伪装成普通编辑推荐。",
      },
      {
        question: "可以投放联盟链接吗？",
        answer: "可以，但必须使用已经获批的真实联盟链接，并且页面会保留联盟披露。",
      },
      {
        question: "如何提交我的 AI 工具？",
        answer: "可以使用免费提交入口排队审核，也可以选择 ¥99 加急审核优先处理资料。",
      },
      {
        question: "广告多久可以上线？",
        answer: "首期采用人工确认。素材、位置和排期确认后，再通过微信或邮件沟通上线时间。",
      },
    ],
  },
  ads: {
    banner: {
      label: "广告",
      eyebrow: "品牌合作",
      title: "让你的 AI 产品被更多人发现",
      description: "触达正在主动寻找 AI 工具的高意向用户。",
      cta: "了解合作",
      url: "advertise.html",
    },
    native: {
      label: "广告",
      title: "这里可以展示你的产品",
      description: "原生广告位，样式与工具内容流自然融合。",
      cta: "预订广告位",
      url: "advertise.html",
    },
  },
};
