window.AI_DIRECTORY_DATA = {
  categories: [
    "全部",
    "AI 对话",
    "图像设计",
    "视频创作",
    "办公效率",
    "编程开发",
    "音频音乐",
  ],
  keywords: ["写作", "绘图", "视频", "编程"],
  tools: [
    {
      name: "ChatGPT",
      description: "全能型 AI 助手，适合对话、写作、分析和日常创作。",
      category: "AI 对话",
      tags: ["热门", "写作"],
      url: "https://chatgpt.com/",
      accent: "#74aa9c",
      featured: true,
    },
    {
      name: "Claude",
      description: "擅长长文本理解、严谨写作和复杂任务协作。",
      category: "AI 对话",
      tags: ["长文本", "写作"],
      url: "https://claude.ai/",
      accent: "#d97757",
    },
    {
      name: "Gemini",
      description: "Google 推出的多模态 AI 助手，连接多种生产力服务。",
      category: "AI 对话",
      tags: ["多模态", "免费"],
      url: "https://gemini.google.com/",
      accent: "#4f86f7",
    },
    {
      name: "豆包",
      description: "面向中文用户的 AI 助手，覆盖问答、写作和图像生成。",
      category: "AI 对话",
      tags: ["中文", "免费"],
      url: "https://www.doubao.com/",
      accent: "#4975f7",
    },
    {
      name: "Midjourney",
      description: "高质量 AI 图像生成工具，适合概念设计与视觉创意。",
      category: "图像设计",
      tags: ["绘图", "热门"],
      url: "https://www.midjourney.com/",
      accent: "#f3f4f6",
      featured: true,
    },
    {
      name: "Canva AI",
      description: "在 Canva 中快速生成图片、文案和完整视觉设计。",
      category: "图像设计",
      tags: ["设计", "模板"],
      url: "https://www.canva.com/ai-image-generator/",
      accent: "#7d2ae8",
    },
    {
      name: "Adobe Firefly",
      description: "Adobe 的生成式创意工具，支持图像生成与智能编辑。",
      category: "图像设计",
      tags: ["绘图", "商用"],
      url: "https://firefly.adobe.com/",
      accent: "#ff5b35",
    },
    {
      name: "Runway",
      description: "专业 AI 视频生成与编辑平台，适合短片和商业创作。",
      category: "视频创作",
      tags: ["视频", "专业"],
      url: "https://runwayml.com/",
      accent: "#d8ff43",
      featured: true,
    },
    {
      name: "剪映",
      description: "一站式智能视频创作工具，提供字幕、数字人和智能剪辑。",
      category: "视频创作",
      tags: ["视频", "中文"],
      url: "https://www.capcut.cn/",
      accent: "#00e5ff",
    },
    {
      name: "Pika",
      description: "通过文字或图片快速生成短视频和创意特效。",
      category: "视频创作",
      tags: ["视频", "特效"],
      url: "https://pika.art/",
      accent: "#facc15",
    },
    {
      name: "Notion AI",
      description: "集成在 Notion 中的写作、总结和知识整理助手。",
      category: "办公效率",
      tags: ["写作", "笔记"],
      url: "https://www.notion.so/product/ai",
      accent: "#f5f5f5",
    },
    {
      name: "Gamma",
      description: "用 AI 快速创建演示文稿、文档和网页。",
      category: "办公效率",
      tags: ["PPT", "演示"],
      url: "https://gamma.app/",
      accent: "#a78bfa",
      featured: true,
    },
    {
      name: "Perplexity",
      description: "带来源引用的 AI 搜索工具，适合资料检索和研究。",
      category: "办公效率",
      tags: ["搜索", "研究"],
      url: "https://www.perplexity.ai/",
      accent: "#20b8cd",
    },
    {
      name: "Cursor",
      description: "以 AI 为核心的代码编辑器，支持生成、理解和修改项目。",
      category: "编程开发",
      tags: ["编程", "热门"],
      url: "https://www.cursor.com/",
      accent: "#e5e7eb",
      featured: true,
    },
    {
      name: "GitHub Copilot",
      description: "集成主流开发环境的 AI 编程助手与代码协作工具。",
      category: "编程开发",
      tags: ["编程", "开发"],
      url: "https://github.com/features/copilot",
      accent: "#8b5cf6",
    },
    {
      name: "Replit",
      description: "在浏览器中用 AI 构建、运行并部署应用。",
      category: "编程开发",
      tags: ["编程", "部署"],
      url: "https://replit.com/",
      accent: "#f26207",
    },
    {
      name: "Suno",
      description: "输入提示词即可生成完整歌曲、伴奏与人声。",
      category: "音频音乐",
      tags: ["音乐", "热门"],
      url: "https://suno.com/",
      accent: "#f43f5e",
      featured: true,
    },
    {
      name: "ElevenLabs",
      description: "高自然度 AI 语音生成、配音与声音设计平台。",
      category: "音频音乐",
      tags: ["语音", "配音"],
      url: "https://elevenlabs.io/",
      accent: "#e5e7eb",
    },
    {
      name: "Udio",
      description: "通过文字描述创作不同风格的完整音乐作品。",
      category: "音频音乐",
      tags: ["音乐", "创作"],
      url: "https://www.udio.com/",
      accent: "#60a5fa",
    },
  ],
  ads: {
    banner: {
      label: "广告",
      eyebrow: "品牌合作",
      title: "让你的 AI 产品被更多人发现",
      description: "触达正在主动寻找 AI 工具的高意向用户。",
      cta: "了解合作",
      url: "#advertise",
    },
    native: {
      label: "广告",
      title: "这里可以展示你的产品",
      description: "原生广告位，样式与工具内容流自然融合。",
      cta: "预订广告位",
      url: "#advertise",
    },
  },
};
