window.AETHER_GROWTH_DATA = {
  brand: {
    name: "AETHER",
    offer: "AI 工具导航广告合作",
    contact: "微信 793679928 / 邮箱 793679928@qq.com",
  },
  links: {
    advertise: "https://ai-tools-directory-swart.vercel.app/advertise.html",
    submit: "https://ai-tools-directory-swart.vercel.app/submit-tool.html",
  },
  segments: [
    {
      name: "AI 工具开发者",
      pain: "产品做出来后缺少第一批中文用户和反馈。",
      where: "V2EX、即刻、掘金、Product Hunt、独立开发者社群。",
      offer: "精选工具置顶或首发组合套餐。",
    },
    {
      name: "SaaS / 插件团队",
      pain: "需要低成本测试中文市场转化，不想一开始买大额广告。",
      where: "知乎、掘金、LinkedIn、微信群、B 站动态。",
      offer: "内容流原生广告或首页横幅。",
    },
    {
      name: "自媒体工具与课程方",
      pain: "想触达学生、自媒体、跨境电商和程序员等细分人群。",
      where: "小红书、知乎、公众号、B 站、垂直社群。",
      offer: "专题页合作、首页横幅或组合套餐。",
    },
    {
      name: "跨境电商 AI 工具",
      pain: "需要接触做 Listing、图片、视频、客服和选品的用户。",
      where: "跨境卖家社群、小红书、知乎、独立站卖家圈。",
      offer: "跨境专题页导流和内容流广告。",
    },
  ],
  posts: [
    {
      id: "day1-a",
      day: "第 1 天",
      platform: "微信朋友圈 / 允许推广的 AI 社群",
      audience: "AI 工具开发者、独立开发者",
      goal: "直接找首批广告客户",
      visualTitle: "AI 产品冷启动？",
      visualSubtitle: "AETHER 首批广告位开放，¥99 起",
      cta: "查看 Media Kit",
      linkType: "advertise",
      text: "AETHER AI 工具导航开放首批广告位。\n\n适合 AI 工具、SaaS、插件、独立开发者产品做中文用户冷启动。\n\n首发合作：\n- 精选工具置顶 ¥99 / 30 天\n- 内容流原生广告 ¥199 / 30 天\n- 首页横幅 ¥299 / 30 天\n- 首发组合套餐 ¥499 / 30 天\n\n广告会明确标注，不承诺点击或成交，但适合低成本测试第一批中文用户。\n\n需要 Media Kit 可以私信我。",
      hashtags: ["#AI工具", "#独立开发", "#SaaS增长", "#广告合作"],
    },
    {
      id: "day1-b",
      day: "第 1 天",
      platform: "小红书",
      audience: "AI 产品负责人、工具开发者",
      goal: "用痛点内容吸引私信",
      visualTitle: "做了 AI 工具没人看见？",
      visualSubtitle: "先用低成本曝光验证中文用户",
      cta: "AETHER 广告合作",
      linkType: "advertise",
      text: "很多 AI 工具不是产品差，而是第一批用户看不到。\n\n我做了一个中文 AI 工具导航 AETHER，正在开放首批广告位，适合：\n1. AI 工具冷启动\n2. SaaS 测试中文市场\n3. 插件 / 小工具找第一批用户\n4. 自媒体工具做曝光\n\n首发价 ¥99 起，人工确认后展示。\n想看位置和价格，可以私信“AI广告”。",
      hashtags: ["#AI工具推荐", "#AI创业", "#副业工具", "#独立开发"],
    },
    {
      id: "day2-a",
      day: "第 2 天",
      platform: "知乎",
      audience: "AI 工具团队、SaaS 运营",
      goal: "用问答内容建立信任",
      visualTitle: "AI 工具怎么找第一批用户？",
      visualSubtitle: "先从垂直导航和专题内容开始",
      cta: "查看合作页",
      linkType: "advertise",
      text: "如果一个 AI 工具刚上线，最不建议一开始就买大预算广告。\n\n更稳的方式是：\n- 先找垂直用户聚集地\n- 用低成本广告位测试点击和私信\n- 把产品放进场景化专题页\n- 看用户是否真的愿意试用\n\nAETHER 是一个中文 AI 工具导航，现在开放首批广告合作位，适合 AI 工具和 SaaS 做冷启动测试。",
      hashtags: ["#AI工具", "#SaaS", "#增长", "#产品冷启动"],
    },
    {
      id: "day2-b",
      day: "第 2 天",
      platform: "V2EX / 独立开发者社区",
      audience: "独立开发者、插件作者",
      goal: "寻找愿意尝试低价广告的开发者",
      visualTitle: "独立开发产品需要曝光吗？",
      visualSubtitle: "AETHER 开放首批赞助位",
      cta: "¥99 起测试",
      linkType: "advertise",
      text: "做了一个中文 AI 工具导航 AETHER，目前工具库和专题页已经上线。\n\n现在开放首批赞助位，主要面向 AI 工具、浏览器插件、开发者工具和小型 SaaS。\n\n价格先保持很低：¥99 起，适合测试有没有中文用户愿意点进去看。\n\n如果你的产品适合 AI 用户，可以发我产品链接，我先人工看是否适合收录或投放。",
      hashtags: ["#独立开发", "#AI工具", "#冷启动", "#产品推广"],
    },
    {
      id: "day3-a",
      day: "第 3 天",
      platform: "掘金",
      audience: "开发者工具、AI 编程产品",
      goal: "找编程类 AI 工具客户",
      visualTitle: "AI 编程工具如何触达开发者？",
      visualSubtitle: "用专题页和导航页做第一层曝光",
      cta: "提交工具",
      linkType: "submit",
      text: "AETHER 已经做了“适合程序员的 AI 工具”专题页。\n\n如果你做的是 AI 编程、代码审查、开发效率、文档生成、测试辅助类产品，可以提交给 AETHER 人工审核。\n\n免费提交会排队；如果想优先处理，也可以申请 ¥99 加急审核。加急只代表优先审核，不保证收录或排名。",
      hashtags: ["#AI编程", "#开发者工具", "#程序员", "#工具推荐"],
    },
    {
      id: "day3-b",
      day: "第 3 天",
      platform: "即刻 / AI 话题",
      audience: "AI 早期产品、创作者工具",
      goal: "引导产品方提交工具",
      visualTitle: "你的 AI 工具被收录了吗？",
      visualSubtitle: "AETHER 支持免费提交和加急审核",
      cta: "提交 AI 工具",
      linkType: "submit",
      text: "AETHER 正在整理中文用户更容易看懂的 AI 工具导航。\n\n如果你有 AI 产品、插件、SaaS 或创作者工具，可以提交给 AETHER 审核。\n\n需要的信息很简单：名称、官网、一句话介绍、分类、价格和联系方式。\n\n适合真实可用、场景明确、对学生/自媒体/程序员/跨境电商有帮助的工具。",
      hashtags: ["#AI产品", "#AI工具导航", "#产品收录", "#效率工具"],
    },
    {
      id: "day4-a",
      day: "第 4 天",
      platform: "B 站动态 / 专栏",
      audience: "AI 工具作者、课程方",
      goal: "用项目复盘吸引合作",
      visualTitle: "AI 工具导航怎么开始变现？",
      visualSubtitle: "广告位、收录、专题页三条线",
      cta: "看 AETHER",
      linkType: "advertise",
      text: "AETHER 的第一阶段变现方式很简单：\n\n1. 工具置顶：适合低成本曝光\n2. 内容流广告：适合自然展示产品卖点\n3. 首页横幅：适合新品发布\n4. 加急审核：适合想优先处理资料的工具方\n\n如果你也在做 AI 工具或课程产品，可以看看 AETHER 的合作页。",
      hashtags: ["#AI工具", "#网站变现", "#独立站", "#增长运营"],
    },
    {
      id: "day4-b",
      day: "第 4 天",
      platform: "小红书",
      audience: "自媒体 AI 工具、内容工具",
      goal: "吸引内容创作工具合作",
      visualTitle: "自媒体 AI 工具想被看见？",
      visualSubtitle: "选题、脚本、封面、视频工具都可提交",
      cta: "提交 / 投放",
      linkType: "submit",
      text: "AETHER 已经做了“适合自媒体的 AI 工具”专题。\n\n如果你的产品能帮助用户做选题、脚本、封面、短视频、配音、音乐或账号运营，可以提交给 AETHER。\n\n也可以选择广告合作，把产品展示给正在寻找 AI 工具的人。",
      hashtags: ["#自媒体工具", "#AI创作", "#短视频工具", "#AI工具"],
    },
    {
      id: "day5-a",
      day: "第 5 天",
      platform: "跨境电商社群 / 允许推广群",
      audience: "跨境电商 AI 工具方",
      goal: "找跨境工具客户",
      visualTitle: "跨境 AI 工具需要中文曝光？",
      visualSubtitle: "Listing、图片、视频、客服工具都适合",
      cta: "跨境专题合作",
      linkType: "advertise",
      text: "AETHER 已上线“适合跨境电商的 AI 工具”专题。\n\n如果你的产品能帮助卖家做 Listing、图片、视频、竞品调研、客服或翻译，可以考虑提交或投放。\n\n首批广告位人工确认，适合先用小预算测试中文卖家用户反馈。",
      hashtags: ["#跨境电商", "#AI工具", "#独立站", "#卖家工具"],
    },
    {
      id: "day5-b",
      day: "第 5 天",
      platform: "知乎",
      audience: "AI 工具购买决策人",
      goal: "解释为什么要投垂直导航",
      visualTitle: "为什么 AI 工具适合投垂直导航？",
      visualSubtitle: "用户已经有明确寻找工具的意图",
      cta: "了解广告位",
      linkType: "advertise",
      text: "垂直 AI 工具导航的价值不是流量最大，而是用户意图更明确。\n\n访问者通常已经在找：\n- 写作工具\n- 绘图工具\n- 视频工具\n- 编程工具\n- 办公效率工具\n\n所以对新工具来说，低成本出现在相关分类或专题里，往往比泛流量更适合做第一轮验证。",
      hashtags: ["#AI工具导航", "#广告投放", "#SaaS增长", "#用户增长"],
    },
    {
      id: "day6-a",
      day: "第 6 天",
      platform: "LinkedIn / 脉脉",
      audience: "AI/SaaS 市场负责人",
      goal: "找 B2B 合作客户",
      visualTitle: "AI / SaaS 中文市场冷启动",
      visualSubtitle: "AETHER 提供低成本首批曝光",
      cta: "联系合作",
      linkType: "advertise",
      text: "AETHER is a Chinese AI tools directory focused on discovery, comparison, and practical use cases.\n\nWe are opening early sponsorship slots for AI tools, SaaS products, plugins, and creator tools that want to test Chinese user interest with a small budget.\n\n合作方式包含精选置顶、内容流原生广告、首页横幅和首发组合套餐。",
      hashtags: ["#AI", "#SaaS", "#Growth", "#ChinaMarket"],
    },
    {
      id: "day6-b",
      day: "第 6 天",
      platform: "公众号 / 私域",
      audience: "已有关系链里的产品方",
      goal: "建立可信度",
      visualTitle: "AETHER 首批合作开放",
      visualSubtitle: "广告、提交、专题页都已上线",
      cta: "查看合作规则",
      linkType: "advertise",
      text: "AETHER 现在有首页、工具库、17 篇 SEO 内容页、广告合作页和提交工具页。\n\n如果你身边有人正在做 AI 工具、SaaS、插件或创作者工具，可以把 AETHER 发给他。\n\n首批合作价格较低，适合产品早期曝光和测试。",
      hashtags: ["#AETHER", "#AI工具", "#产品推广", "#商业合作"],
    },
    {
      id: "day7-a",
      day: "第 7 天",
      platform: "小红书 / 知乎",
      audience: "学生工具、教育工具、学习工具",
      goal: "找教育类 AI 工具客户",
      visualTitle: "学生 AI 工具也可以提交",
      visualSubtitle: "写作、检索、PPT、笔记、编程入门",
      cta: "提交工具",
      linkType: "submit",
      text: "AETHER 已经做了“适合学生的 AI 工具”专题。\n\n如果你的产品适合资料检索、论文辅助、PPT、笔记整理、语言学习或编程入门，可以提交给 AETHER。\n\n我们更看重工具是否真实可用、场景是否清楚，而不是宣传词有多夸张。",
      hashtags: ["#学生工具", "#AI学习", "#AI工具", "#效率工具"],
    },
    {
      id: "day7-b",
      day: "第 7 天",
      platform: "全平台复盘帖",
      audience: "潜在广告客户",
      goal: "制造稀缺感和转化",
      visualTitle: "首批广告位继续开放",
      visualSubtitle: "适合 AI 产品小预算测试",
      cta: "预订广告位",
      linkType: "advertise",
      text: "AETHER 首批广告位继续开放。\n\n当前适合这几类产品：\n- AI 写作 / 绘图 / 视频 / 编程 / 办公工具\n- SaaS 和浏览器插件\n- 自媒体与跨境电商工具\n- 想测试中文用户反馈的新产品\n\n如果你想用较低成本做第一批曝光，可以先看 Media Kit，再决定是否投放。",
      hashtags: ["#AI工具", "#广告位", "#产品冷启动", "#增长"],
    },
  ],
};
